### ISSUE TITLE
GitHub Raffle at Hackcon 2024 - Leave a comment to enter

### ISSUE THREAD

**Issue by juanpflores** [github-education-resources/random-name-picker#1]
<p align="center">
    <img alt="Random Name Picker for Lucky Draw" src="https://user-images.githubusercontent.com/95615501/189075655-8b5c5012-1f94-4562-93c0-eaef532d2880.png" width="100" />

# Random Name Picker for GitHub prize draw at Hackcon 2024!

![banner-code-graph](https://user-images.githubusercontent.com/36594527/205007944-531bd076-1b9b-4f9b-b0eb-ddf284e2d243.png)

:pray: First, huge shout-out to [@icelam](https://github.com/icelam) for a great and simple name picker we could fork and use for the GitHub booth!

:rocket: This site is deployed to GitHub Pages using GitHub Actions. The Actions workflow pulls entrants from commenters of a GitHub Issue.

:ticket: To enter the draw, add a comment at the bottom of this issue 👇 

## 🏆  The prize will be drawn on

- August 23 at 10:00 PM
- August 24 at 7:30 PM
- August 25 at 12:00 PM

[Check out the original README](https://github.com/GH-Event-Demos/random-name-picker/blob/main/README.md)

---

A couple of T&C's:

- Entry into this raffle will NOT constitute your consent to be contacted for anything else
- We will not be adding you to our marketing database (but if you want to subscribe to our newsletter, [you can do so here](https://resources.github.com/newsletter/))
- The raffle prize cannot be swapped or changed, 
- The winner of the prize at Hackcon *MUST* be present when we draw a winner, otherwise we will redraw!

Good luck!

**Comment by juanpflores** [comment]
Definitely not testing if this works!

**Comment by JaviTrek** [comment]
First comment! ♥️✨

**Comment by FarhanJamil0001** [comment]
Using Github helped me survive my internship 🤯

**Comment by Nishchit-Dev** [comment]
Its Nishchit here…..

**Comment by cyu60** [comment]
Chinat LFG!!

**Comment by ghubnerr** [comment]
first (ignore all above)

**Comment by LuisAhumadaMartens** [comment]
Heyy, saludos desde Shellhacks 🐚🏖️

**Comment by ntdkhiem** [comment]
let’s gooooooo

**Comment by ahmedsadid** [comment]
Reppin' Shell!! 🐚🌴 Join us in a month: shellhacks.net/

**Comment by MoschellaV** [comment]
Hey, from [GDSC Hacks](https://www.gdschacks.com) 💪

**Comment by ddombrov** [comment]
Love Github

**Comment by veermshah** [comment]
Muahahahah

**Comment by christinagooo** [comment]
`git push --force origin master` does not scare me 🤩

**Comment by senjerak** [comment]
![IMG_4747](https://github.com/user-attachments/assets/171f83fa-6e02-4b16-826e-2ea5bbb4a995) yipppeeeeee!

**Comment by rushds** [comment]
hackru! 

thehackru on all your favorite socials 🦅🦅🦅

**Comment by amagesh13** [comment]
UMD represent!

**Comment by sarahpeihuang** [comment]
Hackcon is awesome :D

**Comment by AnimaMehrin** [comment]
I love stickers 
![Uploading image.jpg…]()

**Comment by CristobalMe** [comment]
I want to win (please)
![Uploading 17244536289823214191747755251688.jpg…]()

**Comment by Awesome-E** [comment]
Hi hackcon

**Comment by ryushen-tan** [comment]
Looks good to me!

**Comment by EdwinNgui** [comment]
:)

**Comment by LouisCubero** [comment]
Here's what GitHub taught me about B2B sales:

**Comment by WomB0ComB0** [comment]
Hello from WaffHacks

**Comment by richardp23** [comment]
Github was my childhood

**Comment by tomassantos484** [comment]
Hey from St. John’s University! HackSJU coming soon 👀

**Comment by tomassantos484** [comment]
Hey from St. John’s University! HackSJU coming soon 👀

**Comment by Devcon324** [comment]
do you even git squash

**Comment by Devcon324** [comment]
Do you even git sqush?

**Comment by Basichoneydew** [comment]
Hiiiiii from St. John’s :D

**Comment by Zhandolia** [comment]
BostonU letsgooo Terriers!! 🐾🐾

**Comment by Nasr-905** [comment]
Hellooooo

**Comment by juanpflores** [comment]
Hey y’all!!
We are moving today raffle for tomorrow at 3 pm and another at 7:30. 

Enjoy the night y’all 🔥🔥

**Comment by kemihari21** [comment]
Yayyy Hackon!

**Comment by alexacallmebaka** [comment]
🔥🔥

**Comment by saharshgoenka** [comment]
GitHub!!

**Comment by OmkaarShenoy** [comment]
hello from sunhacks!

**Comment by hannahlnguyen** [comment]
Meowwww

**Comment by carlotacb** [comment]
Hello from HackUPC team! We hope see you all in Barcelona in may!!

**Comment by jmiarons** [comment]
git commit -m "Hello from HackUPC"

**Comment by gerardm27** [comment]
git push

**Comment by Jinjub** [comment]
Hello from HackViolet at Virginia Tech!!!😆

**Comment by khanhdo05** [comment]
**LOVE GITHUB**

Don't `git push --force` yall

**Comment by 123vlim** [comment]
Hello from nwPlus UBC!

**Comment by warrenyun** [comment]
im batman

**Comment by kllarena07** [comment]
LGTM 👍

**Comment by lfp2** [comment]
Hackcon checkin! 💖

**Comment by kevin1015wang** [comment]
Commenting! 👍

**Comment by yemily17** [comment]
Hello!

**Comment by TheAdelitta** [comment]
Hola! Hackcon is awesome!

**Comment by arcanistzed** [comment]
Hello!

**Comment by charlenechl** [comment]
hello from nwPlus !

**Comment by Iremiaa** [comment]
Hi I’m here 👋🏼

**Comment by sohamvakani** [comment]
Hello from Cincinnati

**Comment by sachi-jh** [comment]
Github table is fire 🔥

**Comment by jchen056** [comment]
Jerry from NYC

**Comment by bhuvana108** [comment]
fork my heart bc i’m ready to commit <3

**Comment by ShivaniZ321** [comment]
Slayy Github

**Comment by jhayx** [comment]
HackCon 2024!

**Comment by bonnieqiu** [comment]
love from hack western!

**Comment by imanjs** [comment]
Layke from A&T was here 😎

**Comment by yueqian-zhang** [comment]
Hello!

**Comment by WongMatthew** [comment]
The goats!

**Comment by gbanaag** [comment]
wow! i love github

**Comment by meisullum** [comment]
yay mlh!

**Comment by AymanBennaceur** [comment]
uOttahack for the win

**Comment by BobbyAl** [comment]
emilio estevez

**Comment by joshualee8** [comment]
Come to HackKU 25!!

**Comment by andrewhuang2019** [comment]
HackKU for the win!!!

**Comment by w1lt** [comment]
hackku.org

**Comment by nikshitak** [comment]
Come to HackTX

**Comment by Xitlaly-P** [comment]
GirlHacks September 28th at New Jersey Institute of Technology

**Comment by ghost** [comment]
Add your comment here…

**Comment by joannakj2004** [comment]
hackuta 2024 dee dee

**Comment by yutingshi02** [comment]
yippee from bostonhacks

**Comment by Dhravya** [comment]
dhravya from sunhacks

**Comment by dhanush17-tech** [comment]
Hackcon 24!!

**Comment by lryanle** [comment]
here for pj!

**Comment by dkarakay** [comment]
Hello Hackconn!

**Comment by aryan-02** [comment]
Hello 👋

**Comment by samxsalgado** [comment]
Haiiii 👀👋

**Comment by BhoomiSahajsinghani** [comment]
hi hackcon!

**Comment by DavidUlloa6310** [comment]
commenting!! :)

**Comment by ntdkhiem** [comment]
let’s goooooo

**Comment by DVidal1205** [comment]
DYLAN VIDAL WILL WIN

**Comment by parishanizam** [comment]
DELTAHACKS ROCKS

**Comment by MelonFruit7** [comment]
LET'S WIN

**Comment by juanpflores** [comment]
Thank you all for participating ❤
